services:
  prodecryptor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PANTEGNOS_REPO: https://github.com/FrontierTM/Pantegnos.git
        PANTEGNOS_REF: main

    container_name: prodecryptor

    restart: unless-stopped

    environment:
      BOT_TOKEN: ${BOT_TOKEN}

      DATA_DIR: /app/data
      PANTEGNOS_BIN: /opt/pantegnos/pantegnos

      MAX_CONCURRENT_JOBS: 2

    volumes:
      - prodecryptor_data:/app/data

volumes:
  prodecryptor_data:
    name: prodecryptor_data
